sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t rnwkdbs12/reactdev -f Dockerfile.dev .

script:
  - docker run -e CI=true rnwkdbs12/reactdev yarn run test -- --coverage

after_success:
  - echo "Test success"

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker
  env: Docker-env
  bucket_name: elasticbeanstalk-ap-northeast-2-406959428493
  bucket_path: docker
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
